=== Docker Run Log for 6536381 ===
Started at: Mi 29. Okt 16:34:58 CET 2025

[2025-10-29 16:35:08] START: Running container for 6536381
[2025-10-29 16:35:08] SUCCESS: Container 8e8635c452fdaf4c16cd4c2ef6d74b0cd45f216750e101dc0fef2dfd850f2a1e started for 6536381
=== Container logs for 6536381 ===
Traceback (most recent call last):
  File "/snippet.py", line 21, in <module>
    from tastypie.exceptions import ImmediateHttpResponse
  File "/usr/local/lib/python3.11/site-packages/tastypie/exceptions.py", line 102, in <module>
    class ImmediateHttpResponse(TastypieError):
  File "/usr/local/lib/python3.11/site-packages/tastypie/exceptions.py", line 113, in ImmediateHttpResponse
    _response = HttpResponse("Nothing provided.")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/response.py", line 375, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/http/response.py", line 120, in __init__
    content_type = f"text/html; charset={self.charset}"
                                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/response.py", line 168, in charset
    return settings.DEFAULT_CHARSET
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_CHARSET, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
=== End of logs for 6536381 ===
[2025-10-29 16:35:10] INFO: Container 8e8635c452fdaf4c16cd4c2ef6d74b0cd45f216750e101dc0fef2dfd850f2a1e has stopped
