=== Docker Build Log for 2cf4998949f49b58ff284239784e1561 ===
Started at: Mi 29. Okt 13:26:02 CET 2025

[2025-10-29 13:26:02] START: Building image for 2cf4998949f49b58ff284239784e1561
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 256B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.11
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [internal] load build context
#4 transferring context: 2.15kB 0.0s done
#4 DONE 0.0s

#5 [1/5] FROM docker.io/library/python:3.11
#5 CACHED

#6 [2/5] COPY hard-gists/2cf4998949f49b58ff284239784e1561/snippet.py /snippet.py
#6 DONE 0.1s

#7 [3/5] RUN ["pip","install","zipnish"]
#7 1.927 Collecting zipnish
#7 1.964   Downloading zipnish-0.1.5.tar.gz (1.6 MB)
#7 2.052      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.9 MB/s eta 0:00:00
#7 2.154   Preparing metadata (setup.py): started
#7 2.556   Preparing metadata (setup.py): finished with status 'done'
#7 2.585 Collecting simplemysql (from zipnish)
#7 2.596   Downloading simplemysql-1.25.tar.gz (4.5 kB)
#7 2.608   Preparing metadata (setup.py): started
#7 2.712   Preparing metadata (setup.py): finished with status 'done'
#7 2.748 Collecting flask (from zipnish)
#7 2.756   Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
#7 3.043 Collecting sqlalchemy (from zipnish)
#7 3.052   Downloading sqlalchemy-2.0.44-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
#7 3.092 Collecting flask_sqlalchemy (from zipnish)
#7 3.101   Downloading flask_sqlalchemy-3.1.1-py3-none-any.whl.metadata (3.4 kB)
#7 3.142 Collecting blinker>=1.9.0 (from flask->zipnish)
#7 3.150   Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
#7 3.190 Collecting click>=8.1.3 (from flask->zipnish)
#7 3.198   Downloading click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
#7 3.235 Collecting itsdangerous>=2.2.0 (from flask->zipnish)
#7 3.243   Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
#7 3.284 Collecting jinja2>=3.1.2 (from flask->zipnish)
#7 3.294   Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
#7 3.384 Collecting markupsafe>=2.1.1 (from flask->zipnish)
#7 3.392   Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
#7 3.442 Collecting werkzeug>=3.1.0 (from flask->zipnish)
#7 3.450   Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
#7 3.618 Collecting greenlet>=1 (from sqlalchemy->zipnish)
#7 3.626   Downloading greenlet-3.2.4-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
#7 3.673 Collecting typing-extensions>=4.6.0 (from sqlalchemy->zipnish)
#7 3.681   Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
#7 3.814 Collecting mysql-python (from simplemysql->zipnish)
#7 3.824   Downloading MySQL-python-1.2.5.zip (108 kB)
#7 3.837      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.9/108.9 kB 8.9 MB/s eta 0:00:00
#7 3.845   Preparing metadata (setup.py): started
#7 3.932   Preparing metadata (setup.py): finished with status 'error'
#7 3.936   error: subprocess-exited-with-error
#7 3.936   
#7 3.936   × python setup.py egg_info did not run successfully.
#7 3.936   │ exit code: 1
#7 3.936   ╰─> [8 lines of output]
#7 3.936       Traceback (most recent call last):
#7 3.936         File "<string>", line 2, in <module>
#7 3.936         File "<pip-setuptools-caller>", line 34, in <module>
#7 3.936         File "/tmp/pip-install-4fuws3dk/mysql-python_f727a378f362456c9f480d683022472f/setup.py", line 13, in <module>
#7 3.936           from setup_posix import get_config
#7 3.936         File "/tmp/pip-install-4fuws3dk/mysql-python_f727a378f362456c9f480d683022472f/setup_posix.py", line 2, in <module>
#7 3.936           from ConfigParser import SafeConfigParser
#7 3.936       ModuleNotFoundError: No module named 'ConfigParser'
#7 3.936       [end of output]
#7 3.936   
#7 3.936   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 3.937 error: metadata-generation-failed
#7 3.937 
#7 3.937 × Encountered error while generating package metadata.
#7 3.937 ╰─> See above for output.
#7 3.937 
#7 3.937 note: This is an issue with the package mentioned above, not pip.
#7 3.937 hint: See above for details.
#7 4.035 
#7 4.035 [notice] A new release of pip is available: 24.0 -> 25.3
#7 4.035 [notice] To update, run: pip install --upgrade pip
#7 ERROR: process "pip install zipnish" did not complete successfully: exit code: 1
------
 > [3/5] RUN ["pip","install","zipnish"]:
3.937 error: metadata-generation-failed
3.937 
3.937 × Encountered error while generating package metadata.
3.937 ╰─> See above for output.
3.937 
3.937 note: This is an issue with the package mentioned above, not pip.
3.937 hint: See above for details.
4.035 
4.035 [notice] A new release of pip is available: 24.0 -> 25.3
4.035 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:3
--------------------
   1 |     FROM python:3.11
   2 |     COPY hard-gists/2cf4998949f49b58ff284239784e1561/snippet.py /snippet.py
   3 | >>> RUN ["pip","install","zipnish"]
   4 |     RUN ["pip","install","numpy"]
   5 |     RUN ["pip","install","matplotlib"]
--------------------
ERROR: failed to build: failed to solve: process "pip install zipnish" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/plh9r9tki3226c31v4v35ijpw
[2025-10-29 13:26:07] ERROR: Build failed for 2cf4998949f49b58ff284239784e1561
