=== Docker Run Log for 5415296 ===
Started at: Mi 29. Okt 15:40:55 CET 2025

[2025-10-29 15:41:03] START: Running container for 5415296
[2025-10-29 15:41:03] SUCCESS: Container 62316d5cd3c4bc8f277c958b662d3cd17f415a1d018f5dbf21d430e27cf57c57 started for 5415296
=== Container logs for 5415296 ===
Traceback (most recent call last):
  File "/snippet.py", line 3, in <module>
    from django.contrib.auth.views import login
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/views.py", line 11, in <module>
    from django.contrib.auth.forms import (
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/forms.py", line 7, in <module>
    from django.contrib.auth.models import User
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 43, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 131, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
=== End of logs for 5415296 ===
[2025-10-29 15:41:05] INFO: Container 62316d5cd3c4bc8f277c958b662d3cd17f415a1d018f5dbf21d430e27cf57c57 has stopped
