=== Docker Run Log for 7ef2ef722e4520fba09c9f4d83ecc453 ===
Started at: Mi 29. Okt 17:35:01 CET 2025

[2025-10-29 17:35:01] START: Running container for 7ef2ef722e4520fba09c9f4d83ecc453
[2025-10-29 17:35:02] SUCCESS: Container ac579144dbcdfc63fda61454feebea4e233a35e654c04f9cb9dcdb09afc60af3 started for 7ef2ef722e4520fba09c9f4d83ecc453
=== Container logs for 7ef2ef722e4520fba09c9f4d83ecc453 ===
Traceback (most recent call last):
  File "/snippet.py", line 130, in <module>
    response = shopping.search(**{"query": "Python"})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snippet.py", line 76, in search
    return self.request(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snippet.py", line 27, in request
    with urllib.request.urlopen(url) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
=== End of logs for 7ef2ef722e4520fba09c9f4d83ecc453 ===
[2025-10-29 17:35:04] INFO: Container ac579144dbcdfc63fda61454feebea4e233a35e654c04f9cb9dcdb09afc60af3 has stopped
